sudo: required
services:
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPS=1
before_install: 
- openssl aes-256-cbc -K $encrypted_248d61edfafe_key -iv $encrypted_248d61edfafe_iv -in service_account.json.enc -out service_account.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- glcoud auth activate-service-account --key-file service_account.json
- gcloud config set project fibo-complex-calc-k8s
- glcoud config set compute/zone europe-west4-a
- gcloud container clusters get-credentials fibo-cluster
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t zigoto/fibo-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zigoto/fibo-client npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
  