name: Deploy Application
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Client Unit Tests
        run: |-
          docker build -t zigoto/fibo-client -f ./client/Dockerfile.dev ./client
          docker run -e CI=true zigoto/fibo-client npm test
    
  gcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Service Key
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: fibo-cluster
          location: europe-west4-a
  docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - name: Docker login
         run: |-
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo $(pwd)
       
       - name: Docker Build
         run: |-
          docker build -t zigoto/fibo-client:latest -t zigoto/fibo-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t zigoto/fibo-server:latest -t zigoto/fibo-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t zigoto/fibo-worker:latest -t zigoto/fibo-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

       - name: Docker Push
         run: |-
          docker push zigoto/fibo-client:latest
          docker push zigoto/fibo-server:latest
          docker push zigoto/fibo-worker:latest

          docker push zigoto/fibo-client:${{ env.SHA }}
          docker push zigoto/fibo-server:${{ env.SHA }}
          docker push zigoto/fibo-worker:${{ env.SHA }}