apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: standard-rwo 
  resources:
    requests:
      storage: 15Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      component: postgres
